services:
  db:
    image: postgres:15
    container_name: prehab-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prehab_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prehab-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/prehab_db"
      JWT_SECRET: "123456"
      JWT_EXPIRES_IN: "7d"
      JWT_REFRESH_EXPIRES_IN: "30d"
      PORT: 3000

volumes:
  pgdata: